/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SocketChat;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStreamReader;
import java.net.Socket;
import javax.swing.JTextArea;

/**
 *
 * @author Admin
 */
public class ChatPanel extends javax.swing.JPanel {
    
    Socket socket = null;
    BufferedReader bf = null;
    DataOutputStream os = null;
    ReceiveThread t = null;
    String sender;
    String receiver;

    /**
     * Creates new form ChatPanel2
     */
    public ChatPanel(Socket s, String sender, String receiver) {
        initComponents();
        socket = s;
        this.sender = sender;
        this.receiver = receiver;
        try {
            bf = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            os = new DataOutputStream(socket.getOutputStream());
            txtMessages.setText(receiver + " is in\n");
            t = new ReceiveThread(s, txtMessages, sender, receiver);
            t.start();
        } catch (Exception ex) {
            
        }
    }
    
    public JTextArea getTxtMessages() {
        return this.txtMessages;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessages = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        txtMessages.setColumns(20);
        txtMessages.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtMessages.setRows(5);
        jScrollPane1.setViewportView(txtMessages);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tangerine", 1, 36))); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        txtMessage.setColumns(20);
        txtMessage.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtMessage.setRows(5);
        jScrollPane2.setViewportView(txtMessage);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        btnSend.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if (txtMessage.getText().trim().length() == 0) {
            return;
        } else {
            try {
                os.writeBytes(txtMessage.getText());
                os.write(13);
                os.write(10);
                os.flush();
                this.txtMessages.append("\n" + sender + ": " + txtMessage.getText());
                txtMessage.setText("");
            } catch (Exception ex) {
                
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextArea txtMessages;
    // End of variables declaration//GEN-END:variables
}
